# Generated by Django 5.1.3 on 2024-11-23 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_like_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='type',
            field=models.CharField(blank=True, choices=[('like', 'LIKE'), ('dislike', 'DISLIKE')], default=None, max_length=20, null=True),
        ),
    ]
