# Generated by Django 5.1.3 on 2024-11-23 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_like_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='type',
            new_name='like_type',
        ),
    ]
