# Generated by Django 5.1.3 on 2024-11-23 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_rename_type_like_like_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='like_type',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
