# Generated by Django 5.1.3 on 2024-11-24 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_alter_like_like_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='like_type',
            field=models.CharField(blank=True, choices=[('like', 'LIKE'), ('dislike', 'DISLIKE')], default=None, max_length=20, null=True),
        ),
    ]
