# Generated by Django 5.1.3 on 2024-11-24 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_alter_like_like_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='like_type',
            field=models.CharField(choices=[('nothing', 'NOTHING'), ('like', 'LIKE'), ('dislike', 'DISLIKE')], default='nothing', max_length=10),
        ),
    ]
