# Generated by Django 5.1.3 on 2024-11-26 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='like_type',
            field=models.CharField(choices=[('nothing', 'Nothing'), ('like', 'Like'), ('dislike', 'Dislike')], default='nothing', max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='followers', to='posts.userprofile'),
        ),
    ]
