# Generated by Django 5.1.3 on 2024-11-29 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_alter_post_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='user_profile',
        ),
    ]
