# Generated by Django 5.1.3 on 2024-12-09 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0020_post_scheduled_time_alter_post_content_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="tags", to="posts.tag"
            ),
        ),
    ]
