# Generated by Django 5.1.3 on 2024-12-10 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0021_alter_post_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="is_published",
            field=models.BooleanField(default=False),
        ),
    ]
